#!/bin/sh
set -e
case "$1" in
    remove|upgrade|deconfigure)
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q /usr/share/applications 2>/dev/null || true
        fi
        ;;
esac
exit 0
